import json
import logging
from datetime import datetime, timezone
from pathlib import Path


# ---------------------------------------------------------
# Logging Configuration
# ---------------------------------------------------------

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s | %(levelname)s | %(name)s | %(message)s",
)

logger = logging.getLogger("gram_swaram_document_alerts")


# ---------------------------------------------------------
# Configuration
# ---------------------------------------------------------

MONITORING_FILE = Path("88_document_processing_monitoring.json")
ALERTS_FILE = Path("89_document_processing_alerts.json")

FAILURE_WARNING_THRESHOLD = 10.0
FAILURE_CRITICAL_THRESHOLD = 20.0
CHANGE_WARNING_THRESHOLD = 30.0


# ---------------------------------------------------------
# Load Monitoring Data
# ---------------------------------------------------------

def load_monitoring_data() -> dict:
    """Load monitoring data generated by Exercise 88."""

    if not MONITORING_FILE.exists():
        logger.error(
            "Monitoring file not found: %s",
            MONITORING_FILE,
        )
        raise FileNotFoundError(
            f"{MONITORING_FILE} was not found."
        )

    logger.info(
        "Loading monitoring data from %s",
        MONITORING_FILE,
    )

    with MONITORING_FILE.open(
        "r",
        encoding="utf-8",
    ) as file:
        return json.load(file)


# ---------------------------------------------------------
# Create Alert
# ---------------------------------------------------------

def create_alert(
    severity: str,
    alert_type: str,
    message: str,
    metric: str,
    value: float,
    threshold: float | None = None,
) -> dict:
    """Create a structured alert."""

    alert = {
        "timestamp": datetime.now(
            timezone.utc
        ).isoformat(),
        "severity": severity,
        "alert_type": alert_type,
        "message": message,
        "metric": metric,
        "value": value,
        "threshold": threshold,
    }

    logger.info(
        "Alert generated | severity=%s | type=%s",
        severity,
        alert_type,
    )

    return alert


# ---------------------------------------------------------
# Detect Alerts
# ---------------------------------------------------------

def detect_alerts(monitoring_data: dict) -> list[dict]:
    """Analyze monitoring metrics and generate alerts."""

    alerts = []

    # The Exercise 88 JSON structure is:
    #
    # {
    #     "monitoring": {
    #         "system_health": "...",
    #         "metrics": {...}
    #     }
    # }

    monitoring = monitoring_data.get(
        "monitoring",
        {},
    )

    system_health = monitoring.get(
        "system_health",
        "UNKNOWN",
    )

    metrics = monitoring.get(
        "metrics",
        {},
    )

    total_events = int(
        metrics.get(
            "total_events",
            0,
        )
    )

    failed_events = int(
        metrics.get(
            "failed_events",
            0,
        )
    )

    failure_rate = float(
        metrics.get(
            "failure_rate_percent",
            0.0,
        )
    )

    change_rate = float(
        metrics.get(
            "change_rate_percent",
            0.0,
        )
    )

    logger.info(
        "Analyzing system health: %s",
        system_health,
    )

    logger.info(
        "Total events: %d",
        total_events,
    )

    logger.info(
        "Failed events: %d",
        failed_events,
    )

    logger.info(
        "Failure rate: %.2f%% | Change rate: %.2f%%",
        failure_rate,
        change_rate,
    )

    # -----------------------------------------------------
    # System Health
    # -----------------------------------------------------

    if system_health == "CRITICAL":

        alerts.append(
            create_alert(
                severity="CRITICAL",
                alert_type="SYSTEM_HEALTH_CRITICAL",
                message=(
                    "Document processing system health "
                    "is critical."
                ),
                metric="failure_rate_percent",
                value=failure_rate,
                threshold=FAILURE_CRITICAL_THRESHOLD,
            )
        )

    elif system_health == "WARNING":

        alerts.append(
            create_alert(
                severity="WARNING",
                alert_type="SYSTEM_HEALTH_WARNING",
                message=(
                    "Document processing system health "
                    "requires attention."
                ),
                metric="failure_rate_percent",
                value=failure_rate,
                threshold=FAILURE_WARNING_THRESHOLD,
            )
        )

    elif system_health == "HEALTHY":

        alerts.append(
            create_alert(
                severity="INFO",
                alert_type="SYSTEM_HEALTH_HEALTHY",
                message=(
                    "Document processing system "
                    "is operating normally."
                ),
                metric="failure_rate_percent",
                value=failure_rate,
                threshold=FAILURE_WARNING_THRESHOLD,
            )
        )

    # -----------------------------------------------------
    # Failure Rate
    # -----------------------------------------------------

    if failure_rate >= FAILURE_CRITICAL_THRESHOLD:

        alerts.append(
            create_alert(
                severity="CRITICAL",
                alert_type="HIGH_FAILURE_RATE",
                message=(
                    "Critical document processing "
                    "failure rate detected."
                ),
                metric="failure_rate_percent",
                value=failure_rate,
                threshold=FAILURE_CRITICAL_THRESHOLD,
            )
        )

    elif failure_rate >= FAILURE_WARNING_THRESHOLD:

        alerts.append(
            create_alert(
                severity="WARNING",
                alert_type="ELEVATED_FAILURE_RATE",
                message=(
                    "Document processing failure rate "
                    "is above the warning threshold."
                ),
                metric="failure_rate_percent",
                value=failure_rate,
                threshold=FAILURE_WARNING_THRESHOLD,
            )
        )

    # -----------------------------------------------------
    # Failed Events
    # -----------------------------------------------------

    if failed_events > 0:

        alerts.append(
            create_alert(
                severity="WARNING",
                alert_type="PROCESSING_FAILURES",
                message=(
                    f"{failed_events} document processing "
                    f"failure(s) detected."
                ),
                metric="failed_events",
                value=failed_events,
                threshold=0,
            )
        )

    # -----------------------------------------------------
    # Change Rate
    # -----------------------------------------------------

    if change_rate >= CHANGE_WARNING_THRESHOLD:

        alerts.append(
            create_alert(
                severity="WARNING",
                alert_type="HIGH_CHANGE_RATE",
                message=(
                    "Document change rate is "
                    "unusually high."
                ),
                metric="change_rate_percent",
                value=change_rate,
                threshold=CHANGE_WARNING_THRESHOLD,
            )
        )

    # -----------------------------------------------------
    # No Processing Events
    # -----------------------------------------------------

    if total_events == 0:

        alerts.append(
            create_alert(
                severity="CRITICAL",
                alert_type="NO_PROCESSING_EVENTS",
                message=(
                    "No document processing events "
                    "were recorded."
                ),
                metric="total_events",
                value=0,
                threshold=1,
            )
        )

    return alerts


# ---------------------------------------------------------
# Save Alerts
# ---------------------------------------------------------

def save_alerts(
    monitoring_data: dict,
    alerts: list[dict],
) -> None:
    """Save alerts to JSON."""

    monitoring = monitoring_data.get(
        "monitoring",
        {},
    )

    output = {
        "generated_at": datetime.now(
            timezone.utc
        ).isoformat(),
        "source": str(MONITORING_FILE),
        "system_health": monitoring.get(
            "system_health",
            "UNKNOWN",
        ),
        "total_alerts": len(alerts),
        "critical_alerts": sum(
            1
            for alert in alerts
            if alert["severity"] == "CRITICAL"
        ),
        "warning_alerts": sum(
            1
            for alert in alerts
            if alert["severity"] == "WARNING"
        ),
        "info_alerts": sum(
            1
            for alert in alerts
            if alert["severity"] == "INFO"
        ),
        "alerts": alerts,
    }

    with ALERTS_FILE.open(
        "w",
        encoding="utf-8",
    ) as file:
        json.dump(
            output,
            file,
            indent=4,
        )

    logger.info(
        "Alerts saved to %s",
        ALERTS_FILE,
    )


# ---------------------------------------------------------
# Display Alerts
# ---------------------------------------------------------

def display_alerts(alerts: list[dict]) -> None:
    """Display alerts in the terminal."""

    print("\n" + "=" * 65)
    print("DOCUMENT PROCESSING ALERTS")
    print("=" * 65)

    if not alerts:
        print("No alerts generated.")
        return

    for index, alert in enumerate(
        alerts,
        start=1,
    ):

        print(f"\nAlert {index}")
        print("-" * 65)
        print(
            f"Severity   : {alert['severity']}"
        )
        print(
            f"Type       : {alert['alert_type']}"
        )
        print(
            f"Message    : {alert['message']}"
        )
        print(
            f"Metric     : {alert['metric']}"
        )
        print(
            f"Value      : {alert['value']}"
        )
        print(
            f"Threshold  : {alert['threshold']}"
        )

    print("\n" + "=" * 65)
    print(
        f"Total Alerts     : {len(alerts)}"
    )
    print(
        "Critical Alerts  : "
        f"{sum(1 for a in alerts if a['severity'] == 'CRITICAL')}"
    )
    print(
        "Warning Alerts   : "
        f"{sum(1 for a in alerts if a['severity'] == 'WARNING')}"
    )
    print(
        "Info Alerts      : "
        f"{sum(1 for a in alerts if a['severity'] == 'INFO')}"
    )
    print("=" * 65)


# ---------------------------------------------------------
# Main
# ---------------------------------------------------------

def main() -> None:
    """Run Exercise 89."""

    logger.info(
        "Starting Document Processing Alerts"
    )

    try:
        monitoring_data = load_monitoring_data()

        alerts = detect_alerts(
            monitoring_data
        )

        save_alerts(
            monitoring_data,
            alerts,
        )

        display_alerts(alerts)

        logger.info(
            "Exercise 89 completed successfully."
        )

    except FileNotFoundError:
        logger.error(
            "Required monitoring file is missing."
        )

    except json.JSONDecodeError:
        logger.exception(
            "Monitoring JSON contains invalid JSON."
        )

    except Exception:
        logger.exception(
            "Unexpected error occurred during Exercise 89."
        )


if __name__ == "__main__":
    main()